# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a75tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.cache/wt [current_project]
set_property parent.project_path E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_mem E:/cortex-m0_example/cortex_m0_seg7/software/code.hex
read_verilog -library xil_defaultlib {
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/cortexm0ds_logic.v
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/CORTEXM0DS.v
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/AHBMUX.v
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/AHBDCD.v
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/AHB2BRAM.v
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/AHB2LED.v
  E:/cortex-m0_example/source/AHB7SEGDEC_V1.v
  E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/sources_1/imports/source/AHBLITE_SYS.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files E:/cortex-m0_example/cortex_m0_seg7/cortex_m0.srcs/constrs_1/new/top.xdc]


synth_design -top AHBLITE_SYS -part xc7a75tfgg484-1 -flatten_hierarchy none -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef AHBLITE_SYS.dcp

catch { report_utilization -file AHBLITE_SYS_utilization_synth.rpt -pb AHBLITE_SYS_utilization_synth.pb }
